/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Room(props) {
  const { nodes, materials, scene } = useGLTF('/room.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={ scene } />
    </group>
  )
}

useGLTF.preload('/room.glb')