/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshCollider, RigidBody } from '@react-three/rapier'

export default function RoomColliders(props) {
  const { nodes, materials, scene } = useGLTF('./room_colls.glb')
  return (
      <group {...props} dispose={null}>
        <RigidBody colliders={"trimesh"} type="fixed">
        <primitive object={ scene } />
        </RigidBody>
        </group>
  )
}

useGLTF.preload('./room_colls.glb')
